name: default_workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.7 ]
    env:
      LOGGING_INI: logging.ini
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install .[tests]
          pip install lib/sgcharts-ml-0.4.0.tar.gz
      - name: Type checks
        run: |
          mypy src
      - name: Tests
        run: |
          pytest -vv --cov=src